### ISSUE TITLE
hyprland-qtutils not installed and in conflict with hyprutils

### ISSUE THREAD

**Issue by mrjxtr** [hyprwm/hyprland-qtutils#3]
When running latest updates to my system which runs `hyprland`, after the reboot, there is notification that pops up saying, "`hyprland-qtutils`  is not installed please consider installing" or something like that.

When I do install it, it apparently is in conflict with `hyprutils` and yay will ask to remove `hyprutils`

What is the best course of action here as I do not want to break anything but the notifications always pops up every time I boot to linux and it is annoying.

**Comment by seangenabe** [comment]
Are you using Arch Linux?

It seems like hyprland-qtutils-git (pkg) has a dependency on hyprland-utils-git (pkg, AUR) which conflicts with hyprland-utils (pkg).

And an equivalent "hyprland-qtutils" (pkg) hasn't been published yet to extra. Ideally hyprland-qtutils (this project) should also be published to extra.

**Comment by takardo** [comment]
i'm on tumbleweed and I cannot resolve this. ive build and installed from source and it still shows up. on the [hyprland wiki ](https://wiki.hyprland.org/Configuring/Variables/) there is a variable for disable_hyprland_qtutils_check but I cannot get this to work in my hyprland.conf file either.

**Comment by mrjxtr** [comment]
> Are you using Arch Linux?
> 
> It seems like hyprland-qtutils-git (pkg) has a dependency on hyprland-utils-git (pkg, AUR) which conflicts with hyprland-utils (pkg).
> 
> And an equivalent "hyprland-qtutils" (pkg) hasn't been published yet to extra. Ideally hyprland-qtutils (this project) should also be published to extra.
> 
> I also agree that the popup would be quite annoying and preferably there should be an option to disable it if it's just an optional dependency.

@seangenabe  Yes I am on arch. and Yes, this is the conflict seems to look like that the pkg is in conflict with the AUR/pkg. 

Are you also having this issue? if so how are you disabling it?

**Comment by MeatH00k** [comment]
On Arch, managed to disable the message by adding the below to my hyprland.conf in the misc section under "look and feel" as per https://wiki.hyprland.org/Configuring/Variables/

`disable_hyprland_qtutils_check = true`

```
misc {
    disable_hyprland_qtutils_check = true
}
```

**Comment by mrjxtr** [comment]
> On Arch, managed to disable the message by adding the below to my hyprland.conf in the misc section under "look and feel" as per https://wiki.hyprland.org/Configuring/Variables/
> 
> `disable_hyprland_qtutils_check = true`
> 
> ```
> misc {
>     disable_hyprland_qtutils_check = true
> }
> ```

Does this only work after the update? because I am trying to add it right now before updating and it days, "it does not exist"
