### ISSUE TITLE
Where to put downloaded hyprland-qtutils ?

### ISSUE THREAD

**Issue by bashprompt** [hyprwm/hyprland-qtutils#4]
Hyprland on openSUSE is complainig about qtutils not installed.
I have tried putting the executables downloaded from here in numerous places and hyprland still says not installed.

(I appears that the Arch package just puts hyprland-dialog and hyprland-update-screen on the PATH.)

Guidance for using hyprland-qtutils downloaded pre-built is appreciated.

x86-64
openSUSE Tumbleweed
hyprland 46.2
hyprland-qtutils v0.1.1
libhyprutils1 0.2.6-10.1

**Comment by vaxerski** [comment]
compile it manually.

Instructions are the same as https://github.com/hyprwm/xdg-desktop-portal-hyprland?tab=readme-ov-file#installing except dependencies differ.
