### ISSUE TITLE
Install guide?

### ISSUE THREAD

**Issue by k1nxx** [hyprwm/hyprland-qtutils#5]
hi lads, im on an opensuse system and everytime i launch hyprland it tells me about installing hyprland-qtutils but i cant find any documentation or anything about how this should be installed, what dep it needs, etc.... can we please get a guide on that?

**Comment by vaxerski** [comment]
same as all hyprland apps, just use cmake.

See the instructions @ xdph for example: https://github.com/hyprwm/xdg-desktop-portal-hyprland

(obviously deps are different though)
