### ISSUE TITLE
NixOS Package

### ISSUE THREAD

**Issue by non-bin** [hyprwm/hyprland-qtutils#6]
If we have an install guide (#5) I'd be happy to add it to the hyprland nix module

**Comment by non-bin** [comment]
nevermind, it's already been merged into testing (https://github.com/NixOS/nixpkgs/pull/367113)

**Comment by ValynTyler** [comment]
> nevermind, it's already been merged into testing ([NixOS/nixpkgs#367113](https://github.com/NixOS/nixpkgs/pull/367113))

Could you explain what this is? What package do I need to install in order to make the error go away on NixOS?

**Comment by non-bin** [comment]
We just need to wait for it to be tested, and merged into unstable. I assume the stable chanel will recieve hypr-qtutils and Hyprland v46 (which needs it) at the same time

**Comment by ValynTyler** [comment]
> We just need to wait for it to be tested, and merged into unstable. I assume the stable chanel will recieve hypr-qtutils and Hyprland v46 (which needs it) at the same time

Oh, I see. Okay. I thought there was something I could do about it right now. Thanks a bunch for the response!
